name: collectData

on:
  push:
    branches: [ "main", "featureDev" ]
  schedule:
  - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: download current json
        env:
          SJ: ${{ secrets.SJ }}
        run: |
          for i in $(seq 1 10);
          do
            echo wget "${SJ}${i}" --quiet -O "${i}.txt"
          done
          ls -la
          #node pr0gram.js
      
      - name: create artifact folder
        run: |
          mkdir output
          #cp data.json output/
            
      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
